bit/bit/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('professors/', include('professor.urls')),
    path('groups/', include('group.urls')),
]

bit/group/urls.py
from django.urls import path

from . import views

app_name = 'group'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
]

bit/professor/urls.py
from django.urls import path

from . import views

app_name = 'professor'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
]

bit/core/models.py
from django.db import models

# Create your models here.

bit/group/models.py
from django.db import models

class Group(models.Model):
    name = models.CharField(max_length=20)
    
    class Meta:
        ordering = ('name',)
    
    def __str__(self):
        return self.name

bit/professor/models.py
from django.contrib.auth.models import User
from django.db import models


class Professor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    first_name = models.CharField(max_length=100, default="")
    last_name = models.CharField(max_length=100, default="")
    address = models.CharField(max_length=255, default="")
    position = models.CharField(max_length=150, default="")
    email = models.EmailField(unique=True, default="") 

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
class Course(models.Model):
    course_name = models.CharField(max_length=255, default="")
    credit = models.IntegerField()
    hours = models.IntegerField()
    professor = models.ForeignKey(Professor, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.course_name
    

bit/student/models.py
from django.contrib.auth.models import User
from django.db import models
from group.models import Group
from professor.models import Course

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    first_name = models.CharField(max_length=100, default="")
    last_name = models.CharField(max_length=100, default="")
    group = models.ForeignKey(Group, on_delete=models.CASCADE, default=None)
    email = models.EmailField(unique=True, default="") 
    chief = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Mark(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    grade = models.FloatField()

    def __str__(self):
        return f"{self.student.first_name} {self.student.last_name} - {self.course.course_name}: {self.grade}"

bit/core/views.py
from django.shortcuts import render
from group.models import Group
from professor.models import Professor

def index(request):
    groups = Group.objects.all()
    professors = Professor.objects.all() 
    return render(request, 'core/index.html', {
        'groups': groups, 
        'professors': professors,
        })

bit/group/views.py
from django.shortcuts import render, get_object_or_404

from .models import Group

def detail(request, pk):
    group = get_object_or_404(Group, pk=pk)

    return render(request, 'group/detail.html', {
        'group': group
    })

bit/professor/views.py
from django.shortcuts import render, get_object_or_404

from .models import Professor

def detail(request, pk):
    professor = get_object_or_404(Professor, pk=pk)

    return render(request, 'professor/detail.html', {
        'professor': professor
    })

bit/student/views.py
from django.shortcuts import render

# Create your views here.

bit/core/templates/core/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock%} BIT</title>
    
    </head>
    
    <body class="bg-gray-700">
        <nav class="px-6 py-6 flex justify-between items-center bg-black">
            <a href="/" class="text-xl font-semibold text-white">BIT</a>
        
            <div class="space-x-6">
                
            </div>
        
        </nav>


        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between text-white bg-gray-900 absolute inset-x-0 bottom-0">Actually i don`t need a footer</footer>
    </body>
</html>

bit/core/templates/core/groups.html
{% extends 'core/base.html' %}

{% block title %}{% endblock %}

{% block content %}

    <h1 class="mb-12 text-2xl text-center">Main page</h1>
    <div class="grid grid-cols-4 ">
        {% for group in groups %}
        
            <div class="group-name">
                <a href="{% url 'group:detail' group.id %}">
                    <h2>{{ group.name }}</h2> 
                </a>
                
            </div>

        {% endfor %}
    </div>

    <div class="grid grid-cols-4 ">
        {% for professor in professors %}
            <div class="professor">
                <a href="{% url 'professor:detail' professor.id %}">
                    <h2>{{ professor.name }}</h2> 
                </a>
                
            </div>

        {% endfor %} 
    </div>
{% endblock %}

bit/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}{% endblock %}

{% block content %}

    <div class="mt-6 px=6 py=12">
        <h2 class="text-center text-2xl">Groups:</h2>

        <div class="flex justify-between">
            {% for group in groups %}

                <div>
                    <a href="{% url 'group:detail' group.id %}">
                        <div>
                            <h2 class="text=xl">{{ group.name }}</h2>
                        </div>
                    </a>
                </div>

            {% endfor %}
        </div>
    </div>
    <div class="mt-6 px=6 py=12">
        <h2 class="text-center text-2xl">Professors:</h2>

        <div class="flex justify-between">
            {% for professor in professors %}
                <div>
                    <a href="{% url 'professor:detail' professor.id %}">
                        <div>
                            <h2 class="text=xl">{{ professor.first_name }} {{ professor.last_name }}</h2>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>


{% endblock %}

bit/group/templates/group/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ group.name }} - Grades{% endblock %}

{% block content %}

    <h1 class="text-3xl text-center text-black">Grades for Group: {{ group.name }}</h1>
    <ul>
        {% for student in group.student_set.all %}
        <li class="text-xl">{{ student.first_name }} {{ student.last_name }}</li>
        <ul>
            {% for mark in student.mark_set.all %}
            <li>{{ mark.course.course_name }}: {{ mark.grade }}</li>
            {% endfor %}
        </ul>
        {% endfor %}
    </ul>
          
{% endblock %}

bit/professor/templates/professor/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ professor.first_name }} {{ professor.last_name }}{% endblock %}

{% block content %}

    <h1 class="text-black text-2xl">Дані про викладача</h1>
    <h2 class="text-black text-xl">{{ professor.first_name }} {{ professor.last_name }}</h2>
    <p class="text-white">{{ professor.position }}</p>
    <p class="text-white">{{ professor.address }}</p>
    <p class="text-white">{{ professor.email }}</p>
          
{% endblock %}